version: "3.7"
services:
  app:
    container_name: app
    build:
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - database
    links:
      - database
    restart: unless-stopped
  database:
    container_name: database
    build:
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./docker/database/mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345600
      MYSQL_DATABASE: example_sms
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345600

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "9500:80"
    depends_on:
      - database
    links:
      - database
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 12345600
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 100000000
