
CREATE DATABASE IF NOT EXISTS example_sms;
USE example_sms;


CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '12345600';
GRANT ALL PRIVILEGES ON example_sms.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;


CREATE DATABASE IF NOT EXISTS testing;
USE testing;


CREATE USER IF NOT EXISTS 'test_user'@'%' IDENTIFIED BY 'testing123';
GRANT ALL PRIVILEGES ON testing.* TO 'test_user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
